import bcrypt from 'bcryptjs';

const data = {
  user: [
    {
      name: 'ayomide',
      email: 'ayomide@gmail.com',
      isAdmin: true,
      password: bcrypt.hashSync('12345'),
    },
    {
      name: 'funmi',
      email: 'funmi@gmail.com',
      isAdmin: false,
      password: bcrypt.hashSync('12345'),
    },
    {
      name: 'victor',
      email: 'victor@gmail.com',
      isAdmin: false,
      password: bcrypt.hashSync('12345'),
    },
  ],
  products: [
    {
      // _id: '1',
      name: 'Nike Slim Shirt',
      slug: 'nike-slim-shirt',
      category: 'Shirts',
      image: '/images/p1.jpg', // Link to the product image
      price: 120,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.4,
      numReviews: 10,
      description: 'High-quality shirt for everyday wear.',
    },
    {
      // _id: '2',
      name: 'Adidas Running Shoes',
      slug: 'adidas-running-shoes',
      category: 'Footwear',
      image: '/images/p2.jpg', // Link to the product image
      price: 85,
      countInStock: 15,
      brand: 'Adidas',
      rating: 4.8,
      numReviews: 20,
      description: 'Comfortable running shoes with excellent grip.',
    },
    {
      // _id: '3',
      name: 'Puma Sports Backpack',
      slug: 'puma-sports-backpack',
      category: 'Accessories',
      image: '/images/p3.jpg', // Link to the product image
      price: 50,
      countInStock: 8,
      brand: 'Puma',
      rating: 4.2,
      numReviews: 12,
      description: 'Spacious backpack for gym or outdoor activities.',
    },
    {
      // _id: '4',
      name: 'Nike Air Max Sneakers',
      slug: 'nike-air-max-sneakers',
      category: 'Footwear',
      image: '/images/p4.jpg', // Link to the product image
      price: 150,
      countInStock: 5,
      brand: 'Nike',
      rating: 4.6,
      numReviews: 15,
      description: 'Stylish sneakers for casual wear.',
    },
    {
      // _id: '5',
      name: 'Adidas Track Jacket',
      slug: 'adidas-track-jacket',
      category: 'Jackets',
      image: '/images/p5.jpg', // Link to the product image
      price: 110,
      countInStock: 12,
      brand: 'Adidas',
      rating: 4.5,
      numReviews: 18,
      description: 'Lightweight jacket for sports and leisure.',
    },
    {
      // _id: '6',
      name: 'Puma Yoga Leggings',
      slug: 'puma-yoga-leggings',
      category: 'Activewear',
      image: '/images/p6.jpg', // Link to the product image
      price: 65,
      countInStock: 20,
      brand: 'Puma',
      rating: 4.0,
      numReviews: 8,
      description: 'Stretchy leggings for yoga and workouts.',
    },
    {
      // _id: '7',
      name: 'Nike Dri-FIT Cap',
      slug: 'nike-dri-fit-cap',
      category: 'Accessories',
      image: '/images/p7.jpg', // Link to the product image
      price: 30,
      countInStock: 25,
      brand: 'Nike',
      rating: 4.2,
      numReviews: 14,
      description: 'Moisture-wicking cap for outdoor activities.',
    },
    {
      // _id: '8',
      name: 'Adidas Soccer Ball',
      slug: 'adidas-soccer-ball',
      category: 'Sports Equipment',
      image: '/images/p8.jpg', // Link to the product image
      price: 25,
      countInStock: 30,
      brand: 'Adidas',
      rating: 4.0,
      numReviews: 22,
      description: 'Durable ball for soccer enthusiasts.',
    },
    {
      // _id: '9',
      name: 'Puma Graphic T-Shirt',
      slug: 'puma-graphic-t-shirt',
      category: 'T-Shirts',
      image: '/images/p9.jpg', // Link to the product image
      price: 40,
      countInStock: 18,
      brand: 'Puma',
      rating: 4.3,
      numReviews: 16,
      description: 'Trendy tee with bold graphics.',
    },
    {
      // _id: '10',
      name: 'Nike Gym Shorts',
      slug: 'nike-gym-shorts',
      category: 'Bottoms',
      image: '/images/p10.jpg', // Link to the product image
      price: 55,
      countInStock: 14,
      brand: 'Nike',
      rating: 4.1,
      numReviews: 11,
      description: 'Breathable shorts for workouts.',
    },

    {
      // _id: '11',
      name: 'Nike Dri-FIT Running Shirt',
      slug: 'nike-dri-fit-running-shirt',
      category: 'Shirts',
      image: '/images/p11.jpg',
      price: 50,
      countInStock: 8,
      brand: 'Nike',
      rating: 4.2,
      numReviews: 12,
      description:
        'Breathable Nike running shirt to keep you cool and comfortable',
    },

    {
      // _id: '12',
      name: 'Adidas Superstar Shoes',
      slug: 'adidas-superstar-shoes',
      category: 'Shoes',
      image: '/images/p12.jpg',
      price: 90,
      countInStock: 0,
      brand: 'Adidas',
      rating: 4.6,
      numReviews: 8,
      description: 'Iconic old school Adidas shoe, perfect for casual wear',
    },

    {
      // _id: '13',
      name: 'Puma Trinomic XT2',
      slug: 'puma-trinomic-xt2',
      category: 'Shoes',
      image: '/images/p13.jpg',
      price: 120,
      countInStock: 2,
      brand: 'Puma',
      rating: 4.3,
      numReviews: 9,
      description: 'Vintage 1990s inspired chunky sneaker from Puma',
    },

    {
      // _id: '14',
      name: 'Nike Pro Cool Compression Shirt',
      slug: 'nike-pro-cool-compression-shirt',
      category: 'Shirts',
      image: '/images/p14.jpg',
      price: 40,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 15,
      description: 'Lightweight Nike compression top enhances performance',
    },

    {
      // _id: '15',
      name: 'Adidas Alphaskin Sport Tights',
      slug: 'adidas-alphaskin-sport-tights',
      category: 'Pants',
      image: '/images/p15.jpg',
      price: 65,
      countInStock: 12,
      brand: 'Adidas',
      rating: 4.1,
      numReviews: 9,
      description:
        'Flexible Adidas compression tights for running and training',
    },
    {
      // _id: '16',
      name: 'Puma Carson Runner Jersey Shorts',
      slug: 'puma-carson-runner-jersey-shorts',
      category: 'Shorts',
      image: '/images/p16.jpg',
      price: 30,
      countInStock: 8,
      brand: 'Puma',
      rating: 3.9,
      numReviews: 7,
      description: 'Breathable Puma running shorts with side pockets',
    },

    {
      // _id: '17',
      name: 'Nike AeroSwift Running Shorts',
      slug: 'nike-aeroswift-running-shorts',
      category: 'Shorts',
      image: '/images/p17.jpg',
      price: 45,
      countInStock: 7,
      brand: 'Nike',
      rating: 4.3,
      numReviews: 11,
      description: 'Ultra lightweight Nike shorts for racing and track',
    },
    {
      // _id: '18',
      name: 'Adidas Condivo Soccer Pants',
      slug: 'adidas-condivo-soccer-pants',
      category: 'Pants',
      image: '/images/p18.jpg',
      price: 60,
      countInStock: 5,
      brand: 'Adidas',
      rating: 4,
      numReviews: 6,
      description:
        'Tapered Adidas soccer pants with sweat-wicking Climalite fabric',
    },

    {
      // _id: '19',
      name: 'Nike Dry Fit Athletic Shirt',
      slug: 'nike-dry-fit-athletic-shirt',
      category: 'Shirts',
      image: '/images/p19.jpg',
      price: 35,
      countInStock: 12,
      brand: 'Nike',
      rating: 4.7,
      numReviews: 13,
      description: 'Lightweight moisture-wicking tee ideal for workouts',
    },

    {
      // _id: '20',
      name: 'Adidas Tiro Pants',
      slug: 'adidas-tiro-pants',
      category: 'Pants',
      image: '/images/p20.jpg',
      price: 55,
      countInStock: 7,
      brand: 'Adidas',
      rating: 4.5,
      numReviews: 10,
      description:
        'Classic Adidas track pants perfect for warmups and training',
    },
    // {
    //   name: 'Puma Panel Sweatshirt',
    //   slug: 'puma-panel-sweatshirt',
    //   category: 'Sweatshirts',
    //   image: '/images/p21.jpg',
    //   price: 65,
    //   countInStock: 9,
    //   brand: 'Puma',
    //   rating: 4.2,
    //   numReviews: 8,
    //   description:
    //     'Sporty cotton-blend Puma sweatshirt with contrast side panel',
    // },
    // {
    //   name: 'Nike Therma Golf Pants ',
    //   slug: 'nike-therma-golf-pants',
    //   category: 'Pants',
    //   image: '/images/p22.jpg',
    //   price: 75,
    //   countInStock: 6,
    //   brand: 'Nike',
    //   rating: 4.8,
    //   numReviews: 7,
    //   description: 'Windproof fleece-lined Nike golf pants for warmth',
    // },

    // {
    //   name: 'Adidas Essentials Fleece Pants',
    //   slug: 'adidas-essentials-fleece-pants',
    //   category: 'Pants',
    //   image: '/images/p22.jpg',
    //   price: 50,
    //   countInStock: 14,
    //   brand: 'Adidas',
    //   rating: 4.3,
    //   numReviews: 12,
    //   description: 'Cozy fleece sweatpants for lounge and casual wear',
    // },

    // {
    //   name: 'Nike Club Fleece Hoodie',
    //   slug: 'nike-club-fleece-hoodie',
    //   category: 'Hoodies',
    //   image: '/images/p23.jpg',
    //   price: 70,
    //   countInStock: 9,
    //   brand: 'Nike',
    //   rating: 4.6,
    //   numReviews: 15,
    //   description: 'Soft inner fleece lined Nike hoodie for warmth',
    // },
    // {
    //   name: 'Adidas Primeblue Training Tights',
    //   slug: 'adidas-primeblue-training-tights',
    //   category: 'Pants',
    //   image: '/images/p24.jpg',
    //   price: 80,
    //   countInStock: 5,
    //   brand: 'Adidas',
    //   rating: 4.2,
    //   numReviews: 13,
    //   description: 'Eco-friendly adidas tights made with recycled materials',
    // },
    // {
    //   name: 'Puma Archive Logo Sweatshorts',
    //   slug: 'puma-archive-logo-sweatshorts',
    //   category: 'Shorts',
    //   image: '/images/p25.jpg',
    //   price: 55,
    //   countInStock: 7,
    //   brand: 'Puma',
    //   rating: 4,
    //   numReviews: 6,
    //   description: 'Retro-inspired cotton jersey sweat shorts from Puma',
    // },

    // {
    //   name: 'Nike Sportswear Club Fleece Sweatpants',
    //   slug: 'nike-sportswear-fleece-sweatpants',
    //   category: 'Pants',
    //   image: '/images/p26.jpg',
    //   price: 65,
    //   countInStock: 11,
    //   brand: 'Nike',
    //   rating: 4.8,
    //   numReviews: 29,
    //   description: 'Everyday Nike fleece sweatpants for comfort and style',
    // },

    // {
    //   name: 'Adidas Own The Run Tee',
    //   slug: 'adidas-own-the-run-tee',
    //   category: 'Shirts',
    //   image: '/images/p27.jpg',
    //   price: 30,
    //   countInStock: 19,
    //   brand: 'Adidas',
    //   rating: 4.4,
    //   numReviews: 20,
    //   description: 'Breathable running t-shirt with bold adidas logo graphic',
    // },

    // {
    //   name: 'Nike Sportswear Futura Icon T-Shirt',
    //   slug: 'nike-sportswear-futura-icon-tshirt',
    //   category: 'Shirts',
    //   image: '/images/p28.jpg',
    //   price: 35,
    //   countInStock: 8,
    //   brand: 'Nike',
    //   rating: 4.3,
    //   numReviews: 10,
    //   description: 'Cotton graphic t-shirt featuring bold Futura logo design',
    // },
    // {
    //   name: 'Adidas Adilette Comfort Slides',
    //   slug: 'adidas-adilette-comfort-slides',
    //   category: 'Sandals',
    //   image: '/images/p29.jpg',
    //   price: 30,
    //   countInStock: 16,
    //   brand: 'Adidas',
    //   rating: 4.7,
    //   numReviews: 29,
    //   description:
    //     'Lightweight Adidas pool slides with quick-dry bandage strap',
    // },
    // {
    //   name: 'Puma Cali Sport Socks',
    //   slug: 'puma-cali-sport-socks',
    //   category: 'Socks',
    //   image: '/images/p30.jpg',
    //   price: 16,
    //   countInStock: 12,
    //   brand: 'Puma',
    //   rating: 4.5,
    //   numReviews: 15,
    //   description: 'Iconic Puma socks to complete your sportstyle look',
    // },

    // {
    //   name: 'Nike One Mid-Calf Socks',
    //   slug: 'nike-one-mid-calf-socks',
    //   category: 'Socks',
    //   image: '/images/p31.jpg',
    //   price: 15,
    //   countInStock: 19,
    //   brand: 'Nike',
    //   rating: 4.7,
    //   numReviews: 26,
    //   description:
    //     'Supportive Dri-FIT mid-calf socks for elite athletic performance',
    // },
    // {
    //   name: 'Adidas Run It 3-Stripes Shorts ',
    //   slug: 'adidas-run-it-3stripes-shorts',
    //   category: 'Shorts',
    //   image: '/images/p32.jpg',
    //   price: 30,
    //   countInStock: 8,
    //   brand: 'Adidas',
    //   rating: 4.4,
    //   numReviews: 12,
    //   description:
    //     'Vented running shorts with signature adidas side stripe detail',
    // },
  ],
};

export default data;
